[WIP] message processing optimizations, multi-codec support
ravenops/rviz pull request #18
Opened 2019-02-14 01:59 UTC by colhom

Most of the changes in this PR focus on allowing Rviz to process frames as quickly as possible. This primarily entailed decoupling and parallelizing:
  * video encoding (we run two encoders per RViz, regular and keyed)
  * dbus back-and-forth
  * Ogre rendering

This PR also introduces multi-codec support, mainly by exposing an `h264_encoder` parameter.

2019-02-22 01:29 UTC, ccpost reviewed
@colhom In general please remember to request review or PRs will go unread.

Python bit LGTM.  @delaneyj is much more qualified than I am to give a 👍 to the RViz C++ parts.

2019-02-26 18:02 UTC, delaneyj requested changes
I love that you are using the signal/slot interface to setup the timer.  Honestly my only concern is the `venc/kvenc` naming.  It makes sense now but maybe extra comments to remind anyone new that this is our key/regular video encoding additions.

2019-02-26 18:05 UTC, colhom commented
haha I thought a game dev would appreciate that. I worry about the threading overhead, we're doing 4 thread spawn/joins per frame. So 4 threads/frame * 10 fps * 20 captures = 800 threads / second. That's a little high... but want to take some time to get the worker queue implementation right so it's this way for now. Apparently reasonably modern linux kernels can easily do thousands of threads per second, so not ideal but should be fine for now :tm:

2019-02-26 18:05 UTC, colhom commented
> I love that you are using the signal/slot interface to setup the timer. Honestly my only concern is the venc/kvenc naming

that edit distance is definitely way too close

2019-02-26 18:14 UTC, delaneyj commented
> haha I thought a game dev would appreciate that. I worry about the threading overhead, we're doing 4 thread spawn/joins per frame. So 4 threads/frame * 10 fps * 20 captures = 800 threads / second. That's a little high... but want to take some time to get the worker queue implementation right so it's this way for now. Apparently reasonably modern linux kernels can easily do thousands of threads per second, so not ideal but should be fine for now

Normally I'd agree but my guess is the mem->GPU bandwidth will be the limiting factor vs the use of threads as signals.  If it becomes a problem then that's a good problem to have.

2019-02-26 18:47 UTC, colhom commented on scripts/rvnbag_play.py
> +        pmsg = rospy.msg.AnyMsg()
Want to call out this bit for future reference, as it took me awhile to figure out how to use the `AnyMsg` class.

It allows you to read and publish a message without de-serializing it, or even having access to it's class definition. This is probably the single biggest source of CPU saving in this PR, as `rvnbag_play.py` was previously deserializing every message (some messages can be > 100mb) before publishing.

2019-02-26 20:26 UTC, colhom commented on scripts/rvnbag_play.py
> +                tcp_nodelay = True,
Another obscure call-out here. This disables a network efficiency optimization when sending ros messages on the wire, which has the downside introducing more variable delay to message publishing.

2019-02-26 20:27 UTC, colhom commented on scripts/rvnbag_play.py
> +                tcp_nodelay = True,
By disabling it, we're trading decreased network/bandwidth efficiency for lower, less variable delays when sending messages.

2019-02-26 20:29 UTC, colhom commented on scripts/rvnbag_play.py
> +                tcp_nodelay = True,
If `tcp_nodelay` is left `False`, then [Nagle's algorithm](https://searchnetworking.techtarget.com/definition/Nagles-algorithm) is used to batch smaller message buffers together in a single TCP tx buffer ( and possibly as well on the rx buffer on the rviz side, would have to read up more)

2019-02-26 20:36 UTC, colhom commented
>  If it becomes a problem then that's a good problem to have.

I think it eventually will, some of the beefier ec2 instances have 4 or more teslas in them, and more than enough CPU to shuffle buffers around. 

What we really want are [go rountines in C++ AKA boost fibers](https://www.boost.org/doc/libs/1_67_0/libs/fiber/doc/html/index.html), so we can keep our nice end-one-end implicit locking scheme and just change the threads to fibers- done.

Pre-req for that is pulling all our stuff out into a separate Catkin package and linking to a newer version of boost. The rest of ROS needs boost 1.5.whatever specifically, which doesn't have fibers.

2019-02-26 21:01 UTC, merged